# Generated by Django 6.0.3 on 2026-03-13 13:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Manager",
            fields=[
                (
                    "manager_id",
                    models.CharField(max_length=32, primary_key=True, serialize=False),
                ),
                ("name", models.CharField(max_length=255)),
            ],
            options={
                "verbose_name": "Менеджер",
                "verbose_name_plural": "Менеджеры",
            },
        ),
        migrations.CreateModel(
            name="PipelineStatus",
            fields=[
                ("status_id", models.IntegerField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100, unique=True)),
                ("stage_order", models.IntegerField()),
                ("is_final", models.BooleanField(default=False)),
            ],
            options={
                "verbose_name": "Статус воронки",
                "verbose_name_plural": "Статусы воронки",
                "ordering": ["stage_order"],
            },
        ),
        migrations.CreateModel(
            name="Lead",
            fields=[
                (
                    "lead_id",
                    models.CharField(max_length=32, primary_key=True, serialize=False),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("source", models.CharField(max_length=255)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "manager",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="leads.manager"
                    ),
                ),
                (
                    "current_status",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="leads.pipelinestatus",
                    ),
                ),
            ],
            options={
                "verbose_name": "Лид",
                "verbose_name_plural": "Лиды",
            },
        ),
        migrations.CreateModel(
            name="LeadStatusHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("changed_at", models.DateTimeField(auto_now_add=True)),
                ("comment", models.TextField(blank=True)),
                (
                    "lead",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="status_history",
                        to="leads.lead",
                    ),
                ),
                (
                    "changed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="leads.manager",
                    ),
                ),
                (
                    "status",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="leads.pipelinestatus",
                    ),
                ),
            ],
            options={
                "verbose_name": "История статуса лида",
                "verbose_name_plural": "История статусов лидов",
                "ordering": ["-changed_at"],
            },
        ),
    ]
